name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Executa uma vez por dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: gabrielreistech  # Substitua pelo seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
